### ISSUE TITLE
Creating New Wallet error -

### ISSUE THREAD

**Issue by purestaketdb** [algorand/py-algorand-sdk#111]
As brought up by a community member, with the removal of the default wallet from the standard Algorand install, creating a new wallet with the Python SDK when no other wallets exist will result in an error and fail. 

https://forum.algorand.org/t/python-sdk-error-creating-a-new-wallet/1656/5

Essentially the API sends back an empty dict {} but the SDK expects:

`{
  "wallets": []
}`

It is not clear if this should be addressed in the Python SDK to handle the empty case or in the Algod API to return the expected message.

**Comment by fabrice102** [comment]
Another person stumbled upon a similar issue: https://forum.algorand.org/t/python-kmdclient-list-wallets-responds-with-wallets/1893/3
