### ISSUE TITLE
Algod v2 client cannot handle msgpack results

### ISSUE THREAD

**Issue by purestaketdb** [algorand/py-algorand-sdk#122]
When msgpack results are requested of an endpoint that allows this, blocks for example, the response from the service cannot correctly handle the binary response in the v2client/alogd.py because the algod_request method attempts to utf-8 decode the response. 

In the v1 client a check is made first if the response is in 'raw' format, and if so, skips past the decode step 

```python       
if raw_response:
    return resp
return json.loads(resp.read().decode("utf-8"))
```

In the v2 client this check is missing 
```python
res = resp.read().decode("utf-8")  
if response_format == "json":
    return json.loads(res) if res else None
else:
    return res
```

and results in an error:

```    
res = resp.read().decode("utf-8") 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 0: invalid start byte
```

Placing the decode into the response_format check results in the expected binary output.

```python       
if response_format == "json":
    res = resp.read().decode("utf-8")  # the problem
    return json.loads(res) if res else None
else:
    return resp.read()
```

**Comment by mjiang102628** [comment]
Looks like this was fixed in this commit: https://github.com/algorand/py-algorand-sdk/commit/72cca3bde89d61d09068db36129e17c4f9153107
