### ISSUE TITLE
retrieve_from_file function is broken

### ISSUE THREAD

**Issue by ejbaran** [algorand/py-algorand-sdk#124]
The `retrieve_from_file` checks for `type` at the wrong level and therefore misses pulling in unsigned transactions. https://github.com/algorand/py-algorand-sdk/blob/737eabe7d07bf6fa36ae0713de4794493876f608/algosdk/future/transaction.py#L1398

**Comment by EvanJRichard** [comment]
Looks like Pavel fixed this in #125 :+1:
