### ISSUE TITLE
What are restrictions for the amounts we can transfer?

### ISSUE THREAD

**Issue by dggsax** [algorand/py-algorand-sdk#14]
*Issue*
When trying to send a transaction with a value the is not an integer, it becomes unhappy and returns an `AlgodHTTPError`, perhaps a message linking to the specific consensus/spec that discusses restrictions on amounts that you can send

*Repro*
Try to issue a transaction with an amount of .00001. It won't be happy

**Comment by EvanJRichard** [comment]
@dggsax I think this is because all units - both for submitting requests and returned from requests - are integer microAlgos, rather than Algos. Good find! I'll make notes and noise that this needs better documenting.

**Comment by rotemh** [comment]
https://github.com/algorand/py-algorand-sdk/blob/9f81d75e70ed5ae559c25322d6582696308eda44/algosdk/transaction.py#L101
