### ISSUE TITLE
Estimating size of a transaction

### ISSUE THREAD

**Issue by CiottiGiorgio** [algorand/py-algorand-sdk#153]
.estimate_size() method inside Transaction class uses constants.num_additional_bytes_after_signing which was removed in commit ec7f143e4b272110848d2bc3adcc0ac119bbd081

**Comment by mjiang102628** [comment]
This is the same issue as https://github.com/algorand/py-algorand-sdk/issues/144, and was fixed in https://github.com/algorand/py-algorand-sdk/pull/147.
