### ISSUE TITLE
SDK missing endpoint /v2/applications/:application-id

### ISSUE THREAD

**Issue by rfustino** [algorand/py-algorand-sdk#159]
There does not appear to be a call in the Python SDK to get application information for this REST API endpoint. I tried client.applications and client.application 

/v2/applications/:application-id

or the doc needs to be updated 

https://py-algorand-sdk.readthedocs.io/en/latest/algosdk/algod.html

**Comment by ian-algorand** [comment]
@rfustino we think this might be a duplicate, going to check through some of the previous work done here and see if it's already done (or if there's another ticket). Let us know if you have any additional insight

**Comment by ian-algorand** [comment]
Closing this issue, dup of https://github.com/algorand/go-algorand-internal/issues/729
