### ISSUE TITLE
account_info fails if account has large number of transactions

### ISSUE THREAD

**Issue by anya2go** [algorand/py-algorand-sdk#170]
When requesting indexer.account_info for an account with a large number of transactions, it errors out with `RemoteDisconnected` error. 

For example: `response = myindexer.account_info(address='5TSQNIL54GB545B3WLC6OVH653SHAELMHU6MSVNGTUNMOEHAMWG7EC3AA4', block=11190569)`

**Comment by ian-algorand** [comment]
@anya2go, Rotem is saying this has been fixed. Can you verify it looks good on your end and close the ticket if it's running as expected?

**Comment by anya2go** [comment]
Issue was fixed by expending the time before timing out
