### ISSUE TITLE
mnemonic.to_public_key

### ISSUE THREAD

**Issue by bhemen** [algorand/py-algorand-sdk#187]
The function mnemonic.to_public_key() returns the *address* not the public key.  The code below highlights the inconsistency:

```
from algosdk import account, mnemonic

sk, addr = account.generate_account()
mnemonic_secret = mnemonic.from_private_key(sk)
pk = mnemonic.to_public_key(mnemonic_secret)
assert pk == addr
addr = account.address_from_private_key(sk)
assert pk == addr
```

Since the [address and the public key are different in Algorand ](https://developer.algorand.org/docs/features/accounts/), I would suggest changing the name of the function to "mnemonic.to_address()" or something similar.

Thanks

**Comment by jkschin** [comment]
@ian-algorand what does the `FDE` label mean? Is the team open to taking PRs for this? I can see that `to_public_key` is being used only in `account_backup_example.py` and `test_unit.py`, but a change of method name would be quite a breaking change for users / other APIs who use this method, so I'm not sure if it's a good idea to change it for semantic reasons.

**Comment by jasonpaulos** [comment]
@jkschin we are open to taking a PR that renames this function to `mnemonic.to_address`, but keeps `mnemonic.to_public_key` as a deprecated method. Like you pointed out, we unfortunately cannot change the functionality of  the existing `mnemonic.to_public_key` function without breaking existing code, however it would be nice to fix this going forward.
