### ISSUE TITLE
Add support for indexer /assets endpoints

### ISSUE THREAD

**Issue by famendola1** [algorand/py-algorand-sdk#194]
According to the Algorand docs there are several /assets endpoints that aren't natively supported by the v2client/IndexerClient class.

[/assets](https://developer.algorand.org/docs/reference/rest-apis/indexer/#get-v2assets)
[/assets/{asset-id}](https://developer.algorand.org/docs/reference/rest-apis/indexer/#get-v2assetsasset-id)
[/assets/{asset-id}/transactions](https://developer.algorand.org/docs/reference/rest-apis/indexer/#get-v2assetsasset-idtransactions)

**Comment by jasonpaulos** [comment]
Hi @famendola1, the IndexerClient already supports those endpoints with these methods:
* [`search_assets()`](https://github.com/algorand/py-algorand-sdk/blob/6b304e4b080d95286f836d8cd6d8cc3aeeefdfd5/algosdk/v2client/indexer.py#L495) accesses the `/assets` endpoint
* [`asset_info()`](https://github.com/algorand/py-algorand-sdk/blob/6b304e4b080d95286f836d8cd6d8cc3aeeefdfd5/algosdk/v2client/indexer.py#L534) accesses the `/assets/{asset-id}` endpoint
* [`search_asset_transactions()`](https://github.com/algorand/py-algorand-sdk/blob/6b304e4b080d95286f836d8cd6d8cc3aeeefdfd5/algosdk/v2client/indexer.py#L406) accesses the `/assets/{asset-id}/transactions` endpoint

I'm closing this issue, but feel free to re-open if this doesn't address your problem.
