### ISSUE TITLE
How do return accounts that holds a definite number of an asset

### ISSUE THREAD

**Issue by ObiajuluM** [algorand/py-algorand-sdk#195]
ps: This is an awesome project, keep up the good work!

I am working with the indexer function, `indexer.IndexerClient.asset_balances()` and I want to return the particular account with x number of an asset where x = 1, not greater or lesser, just spot on 1.
I ran into a problem, the function's parameters `min_balance` and `max_balance`. 
min_balance returns all accounts with an amount greater than 1, which is none because there is only one asset in existence.
max_balance returns all accounts that have an amount less than or equal to 1 this includes the creator account which holds zero(0) balance of this asset and the actual account holding the asset.

Is there any way to query the SDK to return any account with a specific number of an asset, not a range of the number or greater or lesser than the number specified, just the actual number?

I've thought of editing the SDK source code and making it specifically return the account with a specific number of assets, but I am lost 😂, so if there is another solution to my problem or someone can show me where to edit in the SDK source code I would appreciate it.
**thanks**

**Comment by jasonpaulos** [comment]
There's currently no way to search for an exact amount of assets with a single argument, however you can use both `min_balance` and `max_balance` to narrow the range down to a single value. For example, to find all accounts with a balance of exactly 1 unit of an asset, set `min_balance` to 0 and set `max_balance` to 2.

**Comment by ObiajuluM** [comment]
> There's currently no way to search for an exact amount of assets with a single argument, however you can use both `min_balance` and `max_balance` to narrow the range down to a single value. For example, to find all accounts with a balance of exactly 1 unit of an asset, set `min_balance` to 0 and set `max_balance` to 2.

**Comment by ObiajuluM** [comment]
Thanks
