### ISSUE TITLE
No module named algosdk

### ISSUE THREAD

**Issue by Bhaney44** [algorand/py-algorand-sdk#199]
I am working through the [Layla Coin Tutorial](https://developer.algorand.org/tutorials/create-dogcoin/), specifically on [Issue 1](https://github.com/ejbaran/algorand-tutorials-python/issues/1). I started by entering my node directory in a virtual environment. When I went to run the code, the ended up with the following error.

`ImportError: No module named algosdk`

So, I read the docs and checked the `py-algorand-sdk` [GitHub](https://github.com/algorand/py-algorand-sdk#:~:text=the%20Algorand%20network.-,Installation,pip3%20install%20%5Bfile%20name%5D%20.). I then ran the following in the LaylaCoin directory, inside the node directory on my machine.

`pip3 install py-algorand-sdk`

The install command returned the following.

`Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from cffi>=1.4.1->pynacl->py-algorand-sdk) (2.20)`

So, the problem is when running Python in the directory, my machine can't find the `algosdk`. The `algosdk` is installed in a different different directory, which won't allow me to install the `algosdk` in the local directory. As for the solution, my plan moving forward is to uninstall the `algosdk` and then reinstall in the local directory.

**Comment by Bhaney44** [comment]
I uninstalled `py-algorand-sdk` and reinstalled `py-algorand-sdk` in the local directory.

`pip3 uninstall py-algorand-sdk`
`pip3 install py-algorand-sdk`

However, my machine still returns the same error. 

`python run.py`
`ImportError: No module named algosdk`

I will provide updates as they become available. Otherwise, I am happy to get any feedback or suggestions, thanks!

**Comment by Bhaney44** [comment]
I tried [cloning ](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository-from-github/cloning-a-repository)the repository in the local directory.

`git clone https://github.com/algorand/py-algorand-sdk.git`

and 

`https://github.com/algorand/py-algorand-sdk.git/LOCAL/PATH`

But, I am still getting the same error.

**Comment by fabrice102** [comment]
The issue may be that you have multiple installation of Python.

Try to call `pip` using the following syntax:
```bash
python3 -m pip install py-algorand-sdk
```
and to call your script using the same `python3` executable:
```bash
python3 run.py
```

If this does not work, please include the full output of both commands.

**Comment by Bhaney44** [comment]
You solved the issue. Thank you very much @fabrice102 .
