### ISSUE TITLE
Travis CL fails to build (says libtool missing)

### ISSUE THREAD

**Issue by DamianB-BitFlipper** [algorand/py-algorand-sdk#225]
### Subject of the issue

When making a pull request, Travis CL runs automatically. However, it fails to build the docker instance. I looked at the outputs of other people pushing, and they get the same error. So the issue is something with either the Travis configuration or the docker test configuration. Here is a sample error log output:

```
cp -R crypto/libsodium-fork crypto/copies/linux/amd64/libsodium-fork
[91mmake[1]: *** [Makefile:133: crypto/libs/linux/amd64/lib/libsodium.a] Error 1
make: *** [Makefile:22: go-algorand] Error 2
[0mcd crypto/copies/linux/amd64/libsodium-fork && \
	./autogen.sh --prefix /opt/indexer/third_party/go-algorand/crypto/libs/linux/amd64 && \
	./configure --disable-shared --prefix="/opt/indexer/third_party/go-algorand/crypto/libs/linux/amd64" && \
	make && \
	make install
libtool is required, but wasn't found on this system
make[1]: Leaving directory '/opt/indexer/third_party/go-algorand'
```

Here is a pastebin with the entire log file:

https://hastebin.com/ogacamerih.properties

**Comment by algochoi** [comment]
Thank you for reporting this. I think this was fixed by [this PR](https://github.com/algorand/algorand-sdk-testing/pull/139), as we needed to update the `indexer` dockerfile.
