### ISSUE TITLE
Troubleshoot issues with py-algorand-sdk integration tests on Travis

### ISSUE THREAD

**Issue by onetechnical** [algorand/py-algorand-sdk#226]
# Summary

Work on this PR #224 is blocked, because there are errors in travis, which seem unrelated:

```
Step 17/17 : CMD ["/tmp/setup.sh"]
 ---> Running in 34471935a8a6
Removing intermediate container 34471935a8a6
 ---> bbcdf6b046b8
Successfully built bbcdf6b046b8
Successfully tagged sdk-harness-indexer-23x-1:latest
ERROR: for indexer-live  (<Service: indexer-live>, "The command '/bin/sh -c make' returned a non-zero code: 2")
Service 'indexer-live' failed to build: The command '/bin/sh -c make' returned a non-zero code: 2
Makefile:8: recipe for target 'docker-test' failed
make: *** [docker-test] Error 1
```

This is blocking other PRs. It's possible that this is related to the indexer accounting refactor work that is underway, but we should investigate and verify.

**Comment by algobarb** [comment]
Seems like it's related to this algorand-sdk-testing: https://github.com/algorand/algorand-sdk-testing/blob/2776fc0f84302c11835bd2529de2e166ddeb607b/docker-compose.yml

**Comment by bricerisingalgorand** [comment]
https://github.com/algorand/algorand-sdk-testing/blob/master/docker/indexer/Dockerfile

This dockerfile is no longer able to perform the indexer build since it is missing dependencies needed for go-algorand

**Comment by bricerisingalgorand** [comment]
https://github.com/algorand/algorand-sdk-testing/pull/139

I made this PR that looks like it fixes the indexer build issue. I still saw some actual test failures when I ran `make docker-test` with it locally though.
