### ISSUE TITLE
Algoexplorer API 1010 status code check

### ISSUE THREAD

**Issue by barnjamin** [algorand/py-algorand-sdk#237]
## Problem

I've seen several folks in the discord report issues getting started when they try to use the python SDK.  Trying to call against the algoexplorer api returns a status code 1010 from the User Agent check but it presents itself as a json decoder error. 

I believe this may be the line triggering the error but I haven't dug into it. https://github.com/algorand/py-algorand-sdk/blob/develop/algosdk/algod.py#L89

Mostly posting this as a reminder to add a check

## Solution

Add a check for http status code and if 1010, print out an error message that suggests adding `User-Agent` header field

**Comment by barnjamin** [comment]
Would it be better to set a header like `User-Agent: 'py-algorand-sdk'` by default?

**Comment by algochoi** [comment]
Closed by #260
