### ISSUE TITLE
KMD instructions

### ISSUE THREAD

**Issue by tomfrankel** [algorand/py-algorand-sdk#239]

**Comment by tomfrankel** [comment]
From this point it would help to have more instructions, especially related to the data directory path.  I can't get any path to any version of ~/data/kmd-v0.5 or similar to work (MAC/Intel).

<cmd-i>
Before running example.py, start kmd on a private network or testnet node:

$ ./goal kmd start -d [data directory]

<cmd-i>

**Comment by tomfrankel** [comment]
This worked:  
./goal kmd start -d ~/node/data

**Comment by tomfrankel** [comment]
This is helpful to find your algod_address and algod_token.

<img width="1013" alt="Screen Shot 2021-10-03 at 1 35 50 PM" src="https://user-images.githubusercontent.com/22779767/135766605-10cdb6d2-e8a4-427d-8651-757468425023.png">

**Comment by tomfrankel** [comment]
I've been able to set up the node, send Algos to my_address both from the faucet and Coinbase, but the balance still shows 0 microAlgos.

**Comment by bbroder-uji** [comment]
The node will take a long time to spin up to the current round.   You will know this is the case if `goal node status` is not reporting the most recent round found on algo explorer for testnet.  You can wait or use a fast checkpoint to get to your transaction:

https://developer.algorand.org/docs/run-a-node/setup/install/#sync-node-network-using-fast-catchup
