### ISSUE TITLE
TransactionSigner object should provide address

### ISSUE THREAD

**Issue by barnjamin** [algorand/py-algorand-sdk#254]
## Problem
Given a TransactionSigner that has been initialized with secret key or otherwise, we should already know the address. If all we have is the TransactionSigner, constructing a transaction should be possible by calling `TransactionSigner.address()`

## Solution

Implement `address` method to provide the address for a TransactionSigner object

**Comment by jasonpaulos** [comment]
The relationship between a signer and an address may be more complicated. If we had a WalletConnect-backed TransactionSigner that is capable of signing for dozens of accounts. It's not clear what it should return for `address()`.

Is this a blocker for any use cases?

**Comment by barnjamin** [comment]
Not a blocker, hadn't considered that a signer may be generic enough to support more than just the sender.
