### ISSUE TITLE
Contract class should provide an initializer from an interface and app id

### ISSUE THREAD

**Issue by barnjamin** [algorand/py-algorand-sdk#255]
## Problem

Given an interface and app id I should be able to construct a Contract without accessing the fields required.

## Solution
Implement `fromInterface(id, iface)`

```py
def fromInterface(app_id: int, interface: Interface):
    return abi.Contract(interface.name, app_id, interface.methods)
```

**Comment by algochoi** [comment]
Good suggestion - minor details in the ARC has changed so it would probably take in a `networks` parameter instead of `app_id` now. I'd group this change with #264 .

**Comment by algoanne** [comment]
@barnjamin is this still relevant or has this been solved in e.g. beaker?

**Comment by barnjamin** [comment]
We can close this, it might be handy but probably not worth the time until we see folks really asking for it
