### ISSUE TITLE
Implement ABI changes

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/py-algorand-sdk#264]
Implement the changes described in https://github.com/algorandfoundation/ARCs/pull/53

Additionally, the following implementation details should change:
* The atomic transaction composer should not add a group ID if there's only 1 transaction in the group, since it's unnecessary
* The atomic transaction composer should check that the type of a transaction argument (e.g. `pay`, `axfer`, etc.) matches the ABI transaction argument type.

**Comment by jasonpaulos** [comment]
Additionally, the atomic transaction composer should allow app creation & update transactions to be made using the `add_method_call` method

**Comment by algochoi** [comment]
Linked to #251
