### ISSUE TITLE
Setting `on_complete` for `ApplicationCreateTxn`

### ISSUE THREAD

**Issue by cusma** [algorand/py-algorand-sdk#269]
https://github.com/algorand/py-algorand-sdk/blob/fe5af4c44d1ebda954d25e5aba2461d46a8368b5/algosdk/future/transaction.py#L1773

Shouldn't `on_complete` be a `NoOpOC` by default for `ApplicationCreateTxn`? Is it useful to have it as user defined parameter?

**Comment by jasonpaulos** [comment]
It's useful to have this as a user defined parameter because you can do other things besides NoOps. You could opt in during the app creation, or even delete the app immediately after it's created if you want to have a simple throw-away execution environment.
