### ISSUE TITLE
How to switch from testnet to mainnet and vice versa?

### ISSUE THREAD

**Issue by majestique** [algorand/py-algorand-sdk#272]
I checked the docs but I'm not seeing how to change from testnet to mainnet & vice versa.

I'm looking to check the amount of a particular asset have in my wallet

**Comment by algochoi** [comment]
Hey there! Maybe [this doc](https://developer.algorand.org/docs/run-a-node/operations/switch_networks/) will help. When you are starting your node, you just have to specify which genesis block (defined by the `json` file) it should start from using the `-d` flag. From there, you can use the SDKs to interact with your node.

e.g. for a standard MacOS install, starting a testnet node
```
cd ~/node
mkdir testnetdata 
cp ~/node/genesisfiles/testnet/genesis.json ~/node/testnetdata
./goal node start -d ~/node/testnetdata
```

**Comment by winder** [comment]
[Sandbox](https://github.com/algorand/sandbox) is also a good way to easily start different networks to check this sort of thing.
