### ISSUE TITLE
Min fee not used in suggested parameters

### ISSUE THREAD

**Issue by plasmatech8** [algorand/py-algorand-sdk#284]
### Subject of the issue

Note that I have discussed and described the issue [here](https://forum.algorand.org/t/cannot-calculate-suggested-fees-for-inner-transactions/5826/9?u=plasmatech8)

`suggested_params.min_fee` has no effect on the transaction object when passed into a constructor 
i.e.
```python
transaction.PaymentTxn(
    sp=suggusted_params,  
   # ...
)
```

this is because py-algorand-sdk [uses a constant](https://github.com/algorand/py-algorand-sdk/blob/2ef7d3312b6a2bd7bcb2dc430668060ae8ed80d8/algosdk/future/transaction.py#L367-L370) (`constants.min_txn_fee`) instead of the min-fee which is stored in the object (`sp.min_fee`).

```python
if not sp.flat_fee:
  self.fee = max(
      self.estimate_size() * self.fee, constants.min_txn_fee
  )
```

I do not know if this is intentional or not. 

However, it is a little bit more convenient when you want to do fee calculations by setting a min fee equal to a multiple of the number of transactions (namely for inner transactions). Also, will min-fee change in the future? If so then I assume people would get it via suggested params API.

### Your environment

* Python 3.7.6
* py-algorand-sdk==1.9.0

### Steps to reproduce

```python
suggusted_params = client.suggested_params()
suggusted_params.min_fee = 2000
txn = transaction.PaymentTxn(
    sender=sender_addresss,
    sp=suggusted_params,
    receiver=reciever_address,
    amt=amount
)
print(txn.fee)
```

### Expected behaviour

"2000"

### Actual behaviour

"1000"

**Comment by winder** [comment]
At the moment there is rarely any network congestion, so the min fee should always be used.

We can revisit this in the future when that changes.
