### ISSUE TITLE
Faulty check in `indexer_client.asset_balances` method makes it impossible to get balances grater than 0.

### ISSUE THREAD

**Issue by chrisdewa** [algorand/py-algorand-sdk#296]
### Subject of the issue

In the V2 Indexer, when trying to retrieve balances, you cannot specify `min_balance=0` because of the following check, as 0 is falsely: 
```python
        if min_balance:
            query["currency-greater-than"] = min_balance
```

### Your environment

I'm using `py-algorand-sdk==1.8.0` but this issue is present in the `develop` branch of the repository as of 02/23/2022

### Steps to reproduce

1. Set up a v2 indexer client with any node.
2. retreive balances using client.asset_balances(asset_id, min_balance=0)
3. the reponse will be equivalent to client.asset_balances(asset_id)

### Expected behavior

The function should return accounts with balances greater than 0 (as instructions state)

### Actual behavior

The function returns all accounts including those with a balance of 0.

### Solution

Instead of
```python
if min_balance:
    query["currency-greater-than"] = min_balance
```
The code should be:
```py
if min_balance is not None:
    query["currency-greater-than"] = min_balance
```

### Addendum:

This faulty check is actually present in many other places around the sdk including the same function.
I will make a PR if life allows it.
Take care

**Comment by chrisdewa** [comment]
I just noticed there's already PR #271 already addresses this issue, but there's some building error. I hope it's not too much trouble to fix

**Comment by algochoi** [comment]
Thanks for reporting this. I took a look into merging that PR and it looks like the change will not cooperate nicely with our existing tests. We'll have to take a deeper look in to this.

**Comment by aorumbayev** [comment]
For anyone wondering if there is a temporary workaround within the sdk, just call the `indexer_request` directly. 

```python
from algosdk.v2client import indexer

indexer_client = indexer.IndexerClient(
    "",
    "https://algoindexer.algoexplorerapi.io",
    headers={"User-Agent": "algosdk"},
)

response = indexer_client.indexer_request(
    "GET",
    "/assets/{PUT_YOUR_ASA_ID}/balances",
    {"currency-greater-than": 0},
)
```

**Comment by winder** [comment]
This is related to https://github.com/algorand/algorand-sdk-testing/issues/182

**Comment by bigbulb** [comment]
Hello. The issue persists in the latest SDK (2.1.2). Is there any timeline for a fix? Thanks in advance.

**Comment by tzaffi** [comment]
> Hello. The issue persists in the latest SDK (2.1.2). Is there any timeline for a fix? Thanks in advance.

Thanks @bigbulb for closing duplicate #447. There is no ETA at the moment, but I expect to provide a more direct answer in the first week of May.
