### ISSUE TITLE
Upgrade minimum Python version to 3.10

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/py-algorand-sdk#300]
## Problem

Via https://github.com/algorand/pyteal/issues/244, we plan to upgrade the minimum PyTeal Python version to 3.10.  Provided no py-algorand-sdk specific concerns exist, we'd like to make the same change here.

## Solution

We'll need to do the following:
* Provide advance community notice about the upcoming change.
* Update the build to reflect the change in minimum Python version.
* For PyTeal developer convenience, document how to configure a project-specific Python version.

## Dependencies

* Provide _sufficient_ notice for the community to hear about the pending change.
* Consider if community outreach ought to be synced with PyTeal change.

## Urgency

Depends on desire to sync changes with PyTeal minimum version bump.

**Comment by algochoi** [comment]
Some stats on how people are downloading PyTeal here: https://pypistats.org/packages/pyteal

**Comment by michaeldiamant** [comment]
After group discussion, we're opting to bump to Python 3.8 based on a group-generated rubric.

Here's related PRs:
* https://github.com/algorand/py-algorand-sdk/pull/322 - _Add minimum Python version policy to README_
* https://github.com/algorand/py-algorand-sdk/pull/323 - _Bump minimum Python version to 3.8_
* https://github.com/algorand/py-algorand-sdk/pull/325 - _Matrix test across Python versions for unit tests_
