### ISSUE TITLE
Support Box Storage

### ISSUE THREAD

**Issue by algoanne** [algorand/py-algorand-sdk#328]
(WIP) 

We need to support box storage in the SDK's. I see at last 3 tasks to complete this support, but there may be more: 

1. A new endpoint is being created in the indexer issue https://github.com/algorand/indexer/issues/978 . We should be able to call that from the indexer SDK to be able to get boxes. 
2. We should able to specify the boxes that an application call will touch: i.e. ApplicationCallTxn needs a new "boxes" field. 
3. The atomic transaction composer also needs an update to the `add_method_call` function, and possibly some other updates (not well understood by me yet).

**Comment by michaeldiamant** [comment]
Closing - Replaced by https://github.com/algorand/indexer/issues/978 and https://github.com/algorand/algorand-sdk-testing/issues/175.
