### ISSUE TITLE
TypeError: 'PaymentTxn' object is not callable

### ISSUE THREAD

**Issue by kcsuden** [algorand/py-algorand-sdk#375]
I am trying to run the code below and get a TypeError: 'PaymentTxn' object is not callable. From what I have seen this is exactly how you do it. Does someone know what is happening here?

  `from algosdk import account, mnemonic
  from algosdk.constants import microalgos_to_algos_ratio
  from algosdk.v2client import algod
  from algosdk.future.transaction import PaymentTxn
  
  def send_transaction(sender, quantity, receiver, note, sk):
      quantity = int(quantity * microalgos_to_algos_ratio) #quantity is in algos, not microalgos
      params = algod_client().suggested_params()
      note = note.encode()
  
      try:
          unsigned_txn = PaymentTxn(sender, params, receiver, quantity, None, note)
      except Exception as err:
          print(err)
          return False
      signed_txn = unsigned_txn(sk)`

**Comment by MaxKh** [comment]
Replace `signed_txn = unsigned_txn(sk)` with `signed_txn = unsigned_txn.sign(sk)`

**Comment by jasonpaulos** [comment]
It looks like @MaxKh's suggestion works, so I'm closing this. Feel free to reopen if needed

**Comment by Goldenbuilds** [comment]
I keeep getting 'ModuleNotFoundError: No module named 'algosdk.future' for this line: 

from algosdk.future.transaction import PaymentTxn

**Comment by jasonpaulos** [comment]
@Goldenbuilds the `algosdk.future` package does not exist anymore. Try using `algosdk.transaction` instead.
