### ISSUE TITLE
Cannot send multiple logic signatures in Group Transaction

### ISSUE THREAD

**Issue by DamianB-BitFlipper** [algorand/py-algorand-sdk#376]
### Subject of the issue

When I try to send two logic signed payment transactions of type `LogicSigTransaction` as a group transaction, I receive the error:

`algosdk.error.AlgodHTTPError: TransactionPool.Remember: transactionGroup: [0] had zero Group but was submitted in a group of 2`

Some research led me to this issue: https://forum.algorand.org/t/how-do-you-make-atomic-transfer-of-two-different-assets/1493/15 which leads me to believe that the issue is that `LogicSigTransaction` does not have a `group` property.

### Steps to reproduce

1. Create two logic signature transactions in a list [lsig1, lsig2]
2. Attempt to send them as a group atomically.

### Expected behavior

The transaction happily gets sent.

### Actual behavior

Throws a error: `algosdk.error.AlgodHTTPError: TransactionPool.Remember: transactionGroup: [0] had zero Group but was submitted in a group of 2`

**Comment by jasonpaulos** [comment]
Hi @DamianB-BitFlipper, can you please include a runnable example that produces this error?

I do not think the linked thread is relevant. The issue here sounds like you are not using the `assign_group_id` or `calculate_group_id` functions.

**Comment by DamianB-BitFlipper** [comment]
Should I be assigning the group id of the `Transaction` and not the `LogicSigTransaction`? Currently, I call `assign_group_id` on the `LogicSigTransaction`.

**Comment by DamianB-BitFlipper** [comment]
I think that was the issue.

**Comment by jasonpaulos** [comment]
Yes, you must assign a group ID to the `Transaction`. The `LogicSigTransaction` class is only used to wrap a `Transaction` with a LogicSig signature.

**Comment by DamianB-BitFlipper** [comment]
Thanks for the clarifications. Though may I suggest a slightly more user-friendly exception string? The one raised is rather cryptic to someone seeing the error for the first time.
