### ISSUE TITLE
Mnemonic (12 words) to private key

### ISSUE THREAD

**Issue by ctrl-Felix** [algorand/py-algorand-sdk#383]
My main problem is how to generate the private key from a 12 words seed. However, I also want to derivate the private key by using custom Address indexes to get different private keys from the same seed. 

To achieve this I've been using https://github.com/ebellocchia/bip_utils which works pretty good. However, this returns me private keys as plain str: ``3ad4e586e76be33c803fe9431af6f53782d9714d795db830a4b8821f67ed0b3f`` which don't seem to work with algorand.

I guess I am missing some encoding on that string. Or is there another way to convert mnemonics? The built in function doesn't support derivation.

**Comment by winder** [comment]
Depending on what you're trying to accomplish, you might need to convert the mnemonic to bytes. If you want an address, you should convert it into an address object which has a special encoding for the public key.

For reference, you can find our 25 word mnemonic utilities here: https://github.com/algorand/py-algorand-sdk/blob/5860971f3a4d034defc833681053d363a986afd5/algosdk/mnemonic.py

**Comment by ctrl-Felix** [comment]
My use case is to be able to use the seed and get its sub-accounts. For cosmos following code snippet is what I am using:
(https://github.com/ebellocchia/bip_utils as dependency)

```python    
def _account_by_index(self, idx: int) -> tuple[str, str]:
        seed_bytes = Bip39SeedGenerator(SEED).Generate("")
        bip44_mst_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.COSMOS)
        bip44_acc_ctx = bip44_mst_ctx.Purpose().Coin().Account(idx)
        bip44_chg_ctx = bip44_acc_ctx.Change(Bip44Changes.CHAIN_EXT)
        return bip44_chg_ctx.PublicKey().ToAddress(), bip44_chg_ctx.PrivateKey().Raw().ToHex()
```


Now bip-utils is also supporting Algorand but I am not sure yet how to use that private key with python. Maybe it's just somewhere in the docs and I didn't see it.

**Comment by winder** [comment]
They seem to have documentation:
https://github.com/ebellocchia/bip_utils/blob/f172f3c89ad77327d18cd1b5aae29d2400cb5b54/readme/algorand_mnemonic.md

You can also use the mnemonic utilities in our SDK.
