### ISSUE TITLE
TransactionRejectedError not implemented 

### ISSUE THREAD

**Issue by barnjamin** [algorand/py-algorand-sdk#391]
The error used here is never implemented in the errors module:

https://github.com/algorand/py-algorand-sdk/blob/b53a53d4fab7eed6b47a84dfbf01b3e8f9a120d0/algosdk/future/transaction.py#L3204

**Comment by michaeldiamant** [comment]
As part of fixing the issue, I think it's prudent to configure + run mypy as part of CI.  Among other concerns, it catches the class of problem reported in the issue description.

Here's an example output from a local run where I configured mypy:
```
~/dev/py-algorand-sdk develop ⇡45 *1 !1 ?4 ───────────────────────────────────────────  3.8.13  py-algorand-sdk 08:56:10 AM
❯ mypy --show-error-codes algosdk | grep TransactionRejectedError
algosdk/future/transaction.py:3204: error: Module has no attribute "TransactionRejectedError"  [attr-defined]
```

**Comment by michaeldiamant** [comment]
As a heads up here:  https://github.com/algorand/go-algorand/pull/4755/ was merged, which will expose the issue documented here.  Thanks to @barnjamin for pointing it out.

**Comment by michaeldiamant** [comment]
https://github.com/algorand/py-algorand-sdk/pull/396 provides a fix - thanks @jdtzmn!  I'd like to keep the issue open while working through mypy enablement.
