### ISSUE TITLE
V2client.indexer asset_balances greater than 0

### ISSUE THREAD

**Issue by bigbulb** [algorand/py-algorand-sdk#447]
## Problem

Currently, when trying to scan which address are opted in to a specific asset ID, I want to only return the one that have 1 token of this specific asset ID.
However, using the following code, even the wallets opted in to the asset ID and holding 0 are returned:

`response = indexer_client.asset_balances(asset_id=myAssetId, min_balance=0)`

## Solution
Support greater than 0 in _asset_balances_ for the _min_balance_ parameter.

**Comment by tzaffi** [comment]
Hello. I believe that this is the same issue as #296. If you agree, let's close this issue and re-prioritize that one.
