### ISSUE TITLE
py-algorand-sdk 2.1.0 - AlgodClient.account_info() using exclude=True fails

### ISSUE THREAD

**Issue by oysterpack** [algorand/py-algorand-sdk#448]
### py-algorand-sdk 2.1.0 - AlgodClient.account_info() using exclude=True fails

```python
def account_info(
        self, address: str, exclude: Optional[bool] = None, **kwargs: Any
    ) -> AlgodResponseType:
   ...
```

After upgrading to py-algorand-sdk v2.1.0, an explicit `bool` typing was added for the `explicit` arg. I was previously specifying exclude as exclude="all", per the [REST API docs](https://developer.algorand.org/docs/rest-apis/algod/v2/#get-v2accountsaddress), the 'exclude` param type is an enum with values (all, none). 

However, when I use explicit=True, the algod HTTP request fails with the following error message: "algosdk.error.AlgodHTTPError: failed to parse exclude"

NOTE: MyPy caught the typing error. After resolving the typing error, it broke the app.

### Your environment
I am testing against the AlgoKit v0.3.3 managed sandbox, which runs algod v 3.14.2

### Steps to reproduce
Run the below unit test against a local sandbox environment. 

```python
import unittest

from beaker import sandbox

class MyTestCase(unittest.TestCase):
    # test fails
    def test_get_account_info_with_exclude_bool(self):
        account = sandbox.get_accounts().pop()
        algod_client = sandbox.get_algod_client()

        algod_client.account_info(account.address, exclude=True)

    # test passes
    def test_get_account_info_with_exclude_all(self):
        account = sandbox.get_accounts().pop()
        algod_client = sandbox.get_algod_client()

        algod_client.account_info(account.address, exclude="all")


if __name__ == '__main__':
    unittest.main()
```

### Expected behaviour
I expected exclude=True to behave like exclude="all" and exclude=False to behave like exclude="none"

### Actual behaviour
Passing in a boolean raises algosdk.error.AlgodHTTPError: failed to parse exclude

**Comment by bbroder-algo** [comment]
I agree this behavior is unexpected.

**Comment by bbroder-algo** [comment]
https://github.com/algorand/py-algorand-sdk/pull/449
