### ISSUE TITLE
Incorrect type signature for AlgodClient.send_transaction() `txn` param

### ISSUE THREAD

**Issue by oysterpack** [algorand/py-algorand-sdk#456]
### Incorrect type signature for AlgodClient.send_transaction() `txn` param

Currently, `txn` param is typed as `transaction.Transaction`, which is incorrect and raises MyPy type errors
```python
def send_transaction(
        self, txn: "transaction.Transaction", **kwargs: Any
    ) -> str:
```

The correct method type signature should be:
```python
def send_transaction(
        self, txn: SignedTransaction | MultisigTransaction, **kwargs: Any
    ) -> str:
```

while updating the code, I would also make the following change for the type check: remove the type check for not Transaction, and explicitly check for SignedTransaction | MultisigTransaction
```python
    def send_transaction(
        self, txn: "transaction.Transaction", **kwargs: Any
    ) -> str:
        """
        Broadcast a signed transaction object to the network.

        Args:
            txn (SignedTransaction or MultisigTransaction): transaction to send
            request_header (dict, optional): additional header for request

        Returns:
            str: transaction ID
        """
        assert isinstance(signed_txn, SignedTransaction | MultisigTransaction)
        return self.send_raw_transaction(
            encoding.msgpack_encode(txn), **kwargs
        )
```

### Your environment
py-algorand-sdk   v2.1.1

**Comment by barnjamin** [comment]
This makes sense, should also include `LogicSigTransaction`

**Comment by barnjamin** [comment]
Closed by https://github.com/algorand/py-algorand-sdk/pull/457
