### ISSUE TITLE
Minor leftover in `algosdk.transaction`

### ISSUE THREAD

**Issue by cusma** [algorand/py-algorand-sdk#513]
The line [3238](https://github.com/algorand/py-algorand-sdk/blob/develop/algosdk/transaction.py#L3238) in `algosdk.transaction` seems a minor leftover.

Please close this issue if the line is intentional instead.

**Comment by tzaffi** [comment]
I agree that this is not the most idiomatic way to declare and use a constant python, but I wouldn't consider it a bug. Right next to its usage you'll see [this breadcrumb leading to go-algorand](https://github.com/algorand/go-algorand/blob/e466aa18d4d963868d6d15279b1c881977fa603f/libgoal/libgoal.go#L1089-L1090).

**Comment by tzaffi** [comment]
Closing per your request to close if intentional.
