### ISSUE TITLE
Missing allow_unnamed_resources in simulate

### ISSUE THREAD

**Issue by cswenor** [algorand/py-algorand-sdk#536]
## Problem

We need to be able to call simulate without knowing the box references like the other sdks.

## Solution

Add the allow_unnamed_resources flag into the SimulateRequest method.

## Dependencies

I don't believe so.

## Urgency

The urgency is pretty high because the sdk is unusable for the majority of readonly method calls on smart contracts that have unknown box requirements. It is also very important for any method call when you don't know the box resources, because you need to do a simulate call first to get them.

**Comment by jasonpaulos** [comment]
Yes this SDK is a little behind on simulate options support. I'll take a look at updating it next week
